language: node_js
node_js:
    - 8
cache: yarn
before_script:
    - yarn build
script:
    - yarn test
before_deploy:
    - chmod +x ./deploy.sh
deploy:
    provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
