language: node_js
node_js:
    - 8
cache: yarn
before_script:
    - if [ $TRAVIS_BRANCH = "master" ]; then NODE_ENV=production; else NODE_ENV=development; fi;
    - yarn build
script:
    - yarn test
deploy:
    provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
